import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { ThemeProvider } from '@material-ui/styles';
import { AppBar, Box, Button, createTheme, IconButton, Toolbar, Typography } from '@material-ui/core';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import MenuIcon from '@material-ui/icons/Menu';
import Link from 'next/link';
import CssBaseline from '@material-ui/core/CssBaseline';
import { Provider } from 'react-redux';
import { store } from '../redux/store';

let theme = createTheme({
    palette: {
        type: 'dark'
    }
});

function MyApp({Component, pageProps}: AppProps) {

    return <Provider store={store}>
        <ThemeProvider theme={theme}>
            <Box className={styles.container} style={{flexGrow: 1}}>
                <Head>
                    <title>Next.JS/Capacitor DEMO</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <CssBaseline />

                <AppBar position="static">
                    <Toolbar>
                        <IconButton
                            size="medium"
                            edge="start"
                            color="inherit"
                            aria-label="menu"
                        >
                            <MenuIcon />
                        </IconButton>
                        <Box style={{flexGrow: 1, display: 'flex', flexDirection: 'row'}}>
                            <Typography variant="h6" component="div" style={{marginRight: '16pt'}}>
                                Next.JS-Capacitor Demo
                            </Typography>
                            <Box style={{display: 'flex', flexDirection: 'row'}}>
                                <Link href="/">
                                    <a>
                                        <Button>
                                            Home
                                        </Button>
                                    </a>
                                </Link>

                                <Link href="/ssr">
                                    <a>
                                        <Button>
                                            SSR
                                        </Button>
                                    </a>
                                </Link>

                                <Link href="/redux">
                                    <a>
                                        <Button>
                                            Redux
                                        </Button>
                                    </a>
                                </Link>

                                <Link href="/plugin">
                                    <a>
                                        <Button>
                                            Plugin
                                        </Button>
                                    </a>
                                </Link>
                            </Box>
                        </Box>
                        <Link href="/login">
                            <a>
                                <Button>
                                    Login
                                </Button>
                            </a>
                        </Link>
                    </Toolbar>
                </AppBar>

                <main className={styles.main}>
                    <Component {...pageProps} />
                </main>
            </Box>
        </ThemeProvider>
    </Provider>
}

export default MyApp;
